include(Backports/IncludeGuard)
include_guard(GLOBAL)

include(FunctionExtension/increment)
include(FunctionExtension/decrement)
include(FunctionExtension/backup)
include(FunctionExtension/add_library)
include(FunctionExtension/add_executable)
include(FunctionExtension/target_sources)
include(FunctionExtension/find_package)
