if(CMAKE_SYSTEM_NAME STREQUAL "Windows") 
  set(real_size.4BYTE_FLAG "-fdefault_real-4")
  set(real_size.8BYTE_FLAG "-fdefault_real-8")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux" ) 
  set(real_size.4BYTE_FLAG "-fdefault-real-4")
  set(real_size.8BYTE_FLAG "-fdefault-real-8")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin") 
  set(real_size.4BYTE_FLAG "-fdefault-real-4")
  set(real_size.8BYTE_FLAG "-fdefault-real-8")
else()
  message(FATAL_ERROR "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME} Not recognized")
endif()

if( REAL_SIZE STREQUAL "4" ) 
  set(real_size.flag "${real_size.4BYTE_FLAG}")
elseif( REAL_SIZE STREQUAL "8" ) 
  set(real_size.flag "${real_size.8BYTE_FLAG}")
else()
   message(FATAL_ERROR "REAL_SIZE: Option ${REAL_SIZE} Not recognized" )
endif()

unset(real_size.4BYTE_FLAG)
unset(real_size.8BYTE_FLAG)
