macro(previous_add_library target)
  if(NOT previous_add_library_fn)
    set(previous_add_library_fn add_library)
  endif()

  push(previous_add_library_fn)
  set(previous_add_library_fn _${previous_add_library_fn})
  call(${previous_add_library_fn} ${target} "${ARGN}")
  pop(previous_add_library_fn)
endmacro()
