macro(previous_add_library target keyword)
  if(NOT previous_add_library_fn)
    set(previous_add_library_fn add_library)
  endif()

  push(previous_add_library_fn)
  set(previous_add_library_fn _${previous_add_library_fn})
  if(${keyword} STREQUAL "STATIC" OR ${keyword} STREQUAL "SHARED")
    call(${previous_add_library_fn} ${target} ${keyword} ${ARGN} "")
  else()
    call(${previous_add_library_fn} ${target} ${keyword} ${ARGN})
  endif()
  pop(previous_add_library_fn)
endmacro()
