macro(previous_find_package)
  if(NOT previous_find_package_fn)
    set(previous_find_package_fn find_package)
  endif()

  push(previous_find_package_fn)
  set(previous_find_package_fn _${previous_find_package_fn})
  call(${previous_find_package_fn} ${ARGN})
  pop(previous_find_package_fn)
endmacro()
